version: '3.1'

services:
  server:
    image: netm4ul/netm4ul
    container_name: "netm4ul-server"
    command: ["start", "server", "-v"]
    ports:
      - 8080:8080

  nmap:
    image: netm4ul/netm4ul:nmap
    container_name: "netm4ul-client-nmap"
    command: ["start", "client", "-v"]

  masscan:
    image: netm4ul/netm4ul:masscan
    container_name: "netm4ul-client-masscan"
    command: ["start", "client", "-v"]
    
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
